### PR TITLE
Proper multipart HTML email.

### PR DESCRIPTION
**Pull request by ewels**
Better HTML e-mails, sent as valid multipart MIME with a plaintext alternative and attached images. Also saves the plaintext summary to the results, which is useful when trying to read on the terminal.

### CODE REVIEW

**Comment by ewels** [comment]
Also fixes the problem with previously malformed e-mails coming from UPPMAX.

**Comment by chuan-wang** [comment]
@ewels 
Error occurred during test (see below). I guess the `NGI-ChIPseq/assets/sendmail_template.txt` should be renamed as  `NGI-ChIPseq/assets/sendmail_template.html`?
```
[main] ERROR nextflow.script.WorkflowMetadata - Failed to invoke `workflow.onComplete` event handler
java.io.FileNotFoundException: /home/chuanw/.nextflow/assets/ewels/NGI-ChIPseq/assets/sendmail_template.html (No such file or directory)
```
/Chuan

**Comment by ewels** [comment]
Ah sorry, this is what happens when I'm in a rush to leave and skip the local test :)

Fixed and pushed.

**Comment by chuan-wang** [comment]
Tested and both worked!  /chuan

**Pull request merged**
