### PR TITLE
Massive update - cleanup and Docker implementation

### PR DESCRIPTION
**Pull request by ewels**
Two types of changes here, both quite likely to break the pipeline:

1. Moved all of the embedded scripts into their own stand-alone files, bundled with the pipeline in the `./bin` directory
    * Means that they can be run independently of the pipeline
    * Easier to write, maintain and test
    * No need to escape any variable names or anything
    * Scripts now called in pipeline processes
    * Input files have to be handled as command line parameters for each script
2. Moved filename cleaning into the nextflow code, instead of using bash
    * Makes bugfixing processes easier, as the `command.sh` file in the working directory has proper filenames
    * Cleaner / easier to read processes in my opinino

I will try to launch a test for this on Milou now, but would be great if @chuan-wang you could also launch your tests.

Phil

### CODE REVIEW

**Comment by chuan-wang** [comment]
It's so nice that you have started it! I saw your comments in "issues" and was about to do this :p

**Comment by ewels** [comment]
Cool, automated travis builds now seem to be running! eg. see the latest commits have red crosses indicating that they all failed. Clicking them shows you the logs from the runs.

Latest build (still running as I type this) is here: https://travis-ci.org/ewels/NGI-ChIPseq/builds/213504243

Fingers crossed that this one may work! 🤞

**Comment by ewels** [comment]
Damn, something wrong with the BWA index reference. Will look into this tomorrow. From now on, we shouldn't merge any PRs until the automated tests finish and are successful 😁

**Comment by chuan-wang** [comment]
OK! It's really interesting to see how the automated test works! Is it hard to set up?

**Comment by chuan-wang** [comment]
Hi Phil, there seemed to be some problem with the permission of the stand alone scripts:
1) Error in `countstat`: 
```
/home/chuanw/.nextflow/assets/ewels/NGI-ChIPseq/bin/countstat.pl: Permission denied
```
2) Error in `ngs_config_generate`: 
```
/home/chuanw/.nextflow/assets/ewels/NGI-ChIPseq/bin/ngs_config_generate.r: Permission denied
```
3) Error in `calculateNSCRSC`: 
```
/home/chuanw/.nextflow/assets/ewels/NGI-ChIPseq/bin/calculateNSCRSC.r: Permission denied
```
And in deepTools there was an expecting error because I used only 1 sample for test and no correlation matrix could be done. Do you think we should fix it or just let it be?

/chuan

**Comment by ewels** [comment]
Thanks for this Chuan! I'll fix all of these issues before we merge.

**Comment by ewels** [comment]
Tested and works (with docker)

**Comment by chuan-wang** [comment]
Good work!

**Pull request merged**
