### PR TITLE
Config + readme updates

### PR DESCRIPTION
**Pull request by ewels**
Few changes here:

* Updated readme
  * New logo
  * Reordered content a little to make it flow more naturally
  * Added a bit more content in a couple of places
* Updated config file
  * Removed unused reference indices, made config much shorter
  * Combined process config options into blocks (modules + errorStrategy)
  * Fixed a couple of minor bugs (defining undefined params, adding `{}` for some settings where they were required
* Updated script a little
  * Added `--fastqc` to TrimGalore, so FastQC runs after trimming is complete
  * Removed default genome, so no longer runs as Human by default
  * Defined some previously undefined params
  * Moved variable checks above main log header output
  * Moved UPPMAX specific Rlocation default into config file instead of main script
  * Added bash `pipefail` headers so that error logs are more informative.

### CODE REVIEW

**Comment by ewels** [comment]
NB: Haven't tried running this myself yet. Would be nice to set up a docker container for local + automated testing.

**Comment by ewels** [comment]
ps. You can see the updated readme on my repo [here](https://github.com/ewels/NGI-ChIPseq/blob/master/README.md).

**Comment by chuan-wang** [comment]
Tested and worked as expected.

**Comment by ewels** [comment]
Brilliant, thanks! 👍

**Pull request merged**
