### PR TITLE
Add genome files for ngsplot

### PR DESCRIPTION
**Pull request by chuan-wang**

### CODE REVIEW

**Comment by chuan-wang** [comment]
Tested and worked as expected.

**Comment by ewels** [comment]
Hi @chuan-wang - how much filesize does this add to the Docker container?

**Comment by chuan-wang** [comment]
Hi,
It's 40M in total.
/chuan

**Comment by ewels** [comment]
Ok that's fine, as long as it's not multiple GB :) I don't love the idea that we're using export.uppmax.uu.se but I don't have any better ideas at the moment.

Thanks for doing this!

**Comment by chuan-wang** [comment]
Yeah, I also thought for a while. The original ngsplot genome files are stored in a personal google doc drive which made me nervous. I thought it would be more controllable to have them in our test data directory instead.

**Pull request merged**
